# Generated by Django 4.1 on 2022-09-09 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import patient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=3, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telephone/HP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Soaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(max_length=16, unique=True, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time')),
                ('subjective', models.TextField(verbose_name='Subjective')),
                ('objective', models.TextField(verbose_name='Objective')),
                ('assessment', models.TextField(verbose_name='Assessment')),
                ('plan', models.TextField(verbose_name='Plan')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('image', models.ImageField(blank=True, null=True, upload_to='soap/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to=patient.models.Soaps.limit_choices_to_current_user, on_delete=django.db.models.deletion.RESTRICT, to='doctor.doctors', verbose_name='Doctor')),
                ('patient', modelcluster.fields.ParentalKey(limit_choices_to=patient.models.Soaps.limit_choices_to_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='related_patient', to='patient.patients')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOAP',
                'verbose_name_plural': 'SOAP',
                'db_table': 'soaps',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='NextAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date Time')),
                ('patient', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_appointment', to='patient.patients')),
            ],
            options={
                'db_table': 'next_appointment',
            },
        ),
    ]
